// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frtsjyhyfkxtzbvvocoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZydHNqeWh5Zmt4dHpidnZvY29vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNTYzMDAsImV4cCI6MjA3NjgzMjMwMH0.zUgNr5Cxh9J7IY31jwUcJPJz7ZKKjfYp4NRfvjpolwg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});